### PR TITLE
NPE when t.isUid() does not exists

### PR DESCRIPTION
**Pull request by matiasrosemberg**

### CODE REVIEW

**Comment by ilgrosso** [comment]
Mmm commenting out statements is not a fix...

**Comment by ilgrosso** [comment]
You might want to change

```
LOG.ok("Operand is uid: {0}", t.isUid());
```
into something like as
```
LOG.ok("Operand: {0}", t);
```

Also, please open an issue on https://connid.atlassian.net/browse/CMD for this defect, thanks.

**Comment by matiasrosemberg** [comment]
Thanks for the repply, im new on this. i will close this request and start a new issue.

**Comment by ilgrosso** [comment]
No problems: feel free to open a new PR with the suggested change.
Do not forget to include "CMD-8" in the commit message, to bind it to jira.

**Pull request closed without merging**
